server:
  port: 8000

spring:
  application:
    name: xdclass-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: LLkk1010

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.220.131:8848
    sentinel:
      transport:
        dashboard: 192.168.220.131:8084
        port: 9999


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

xdclass-video-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

feign:
  sentinel:
    enabled: true